name: spotify_clone
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: 
  get_it: 
  shared_preferences: 
  dartz: 
  reactive_button: 
  dio: 
  logger: 
  flutter_svg:  
  fan_carousel_image_slider: 
  youtube_player_flutter: 9.0.0
  chewie: ^1.13.0
  video_player: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 300


